#!/usr/bin/env ruby

require 'telegram/bot'

token = %x[cat /etc/bot09/token].strip
bot_username = '@marlonasir_bot'

puts "[INFO] Running bot #{$0}..."

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    puts " => #{message.text}"
    if message.text == "/hello"
      bot.api.send_message(chat_id: message.chat.id, text: "Hello World!")
    elsif message.text == "/byebye"
      bot.api.send_message(chat_id: message.chat.id, text: "Bye bye!")
    elsif message.text == "/help"
      bot.api.send_message(chat_id: message.chat.id, text: "
puedes usarme escribiendo:
/hello
/byebye
/time (hora actual)
/date (fecha actual)
")
     elsif message.text == "/time"
        t = Time.now
 
        bot.api.send_message(chat_id: message.chat.id, text: t.strftime( "%H : %M : %S"))
     elsif message.text == "/date"
         t = Time.now
 
         bot.api.send_message(chat_id: message.chat.id, text: t.strftime("%d/%m/%Y"))
     elsif message.text == "/byebye"
         bot.api.send_message(chat_id: message.chat.id, text: "Bye bye!")  
    end
  end
end
